name: Build

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  windowsBuild:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.5

      - name: Install Haxelibs
        run: |
          haxelib --quiet install lime 7.9.0
          haxelib --quiet install openfl 9.1.0
          haxelib --quiet install flixel 5.0.0
          haxelib --quiet --never run lime setup
          haxelib --quiet install flixel-ui
          haxelib --quiet install flixel-addons 2.11
          haxelib --quiet install hscript
          haxelib --quiet install hxcpp-debug-server
          haxelib --quiet git flxanimate https://github.com/Dot-Stuff/flxanimate.git
          haxelib --quiet install hxCodec 2.5.1
          haxelib --quiet git extension-androidtools https://github.com/MAJigsaw77/extension-androidtools.git
          haxelib --quiet git discord_rpc https://github.com/Aidan63/linc_discord-rpc.git

      - name: Setup Lime
        run: |
          haxelib run lime setup -alias -y
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true
          haxelib set lime 7.9.0
          haxelib set openfl 9.1.0
          haxelib list

      - name: Compile
        run: haxelib run lime build windows -release

      - name: Publish Artifact
        uses: actions/upload-artifact@main
        with:
          name: windowsBuild-release
          path: export/release/windows
